### ISSUE TITLE
[question] How to use py::bool_ in nanobind?

### ISSUE THREAD

**Issue by harsszegi** [wjakob/nanobind#130]
Hi,
I need to create something like this: https://github.com/pybind/pybind11_json
for nanobind and for rapidjson.

I fail to understand how to construct a "bool" binding object with nanobind.
How to create a bool object currently?
Also as I saw "::float_" was also dropped in favor of "::int_", am I getting it right?
Thanks,

**Comment by wjakob** [comment]
Please don't open bug tickets for questions, we have a discussion tab for this.
