### ISSUE TITLE
[BUG]: Having trouble compiling with NVCC

### ISSUE THREAD

**Issue by xingruiy** [wjakob/nanobind#133]
### Problem description

Hi,

I was under the impression that, since the tensor class can have either host or GPU memory, it should be working fine with both C++ and CUDA, but I am having problems compiling a simple code with NVCC. The error message says:

`nvcc fatal   : 's': expected a number`

I have checked the compiler args, it seems a problematic compiler option is causing the issue:

`/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -Dtest_dlpack_EXPORTS --options-file CMakeFiles/test_dlpack.dir/includes_CUDA.rsp -O3 -DNDEBUG --generate-code=arch=compute_52,code=[compute_52,sm_52] -Xcompiler=-fPIC -fno-stack-protector -Os -std=c++17 -MD -MT CMakeFiles/dir/src/bindings.cu.o -MF CMakeFiles/src/bindings.cu.o.d -x cu -rdc=true -c ~/cuda_test/src/bindings.cu -o CMakeFiles/src/bindings.cu.o
`

Could anyone help me solve this issue? A toy example is given below.

### Reproducible example code

```text
`bindings.cu:`

#include <nanobind/nanobind.h>

namespace nb = nanobind;

using namespace nb::literals;

NB_MODULE(test, m) {
    m.def("add", [](int a, int b) { return a + b; }, "a"_a, "b"_a);
}


`CMakeLists.txt:`

cmake_minimum_required(VERSION 3.18...3.22)
project(test_dlpack CUDA CXX)

find_package(Python 3.8 COMPONENTS Interpreter Development.Module REQUIRED)
add_subdirectory(nanobind)

nanobind_add_module(test_dlpack 
    src/bindings.cu
)
```

**Comment by wjakob** [comment]
Hi @xingruiy -- ``nvcc`` is not a compiler that is officially supported by this project. Please use GCC/Clang for the binding parts, and NVCC for your CUDA kernels and launcher code.

**Comment by Jegp** [comment]
For future reference, this was caused by the `-0s` flag sent to NVCC. I resolved this by adding the `NOMINSIZE` flag to the CMakeLists.txt

```cmake
nanobind_add_module(
  aestream_ext 
  NB_STATIC STABLE_ABI LTO  NOMINSIZE
...
)
```
