### ISSUE TITLE
[BUG]: XCode version is not detected when using XCode CLI-only tools, breaking CMake build

### ISSUE THREAD

**Issue by brendan-ward** [wjakob/nanobind#136]
### Problem description

MacOS 12.5, XCode CLI tools installed but not full XCode.

This block in `nanobind-config.cmake` fails:

```
  execute_process(
    COMMAND xcodebuild -version
    OUTPUT_VARIABLE NB_XCODE_VERSION_STR
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_FILE /dev/null)
  string(REGEX MATCH "Xcode ([0-9][0-9]?([.][0-9])+)" NB_XCODE_VERSION_MATCH ${NB_XCODE_VERSION_STR})
```

with this error message:

```
CMake Error at vendor/nanobind/cmake/nanobind-config.cmake:55 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  vendor/nanobind/CMakeLists.txt:73 (find_package)
```

apparently because `NB_XCODE_VERSION_STR` does not get set to a valid value.  Here's what that returns when run directly:

```
❯ xcodebuild -version 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

To resolve this, I replaced 
`COMMAND xcodebuild -version` 
with 
`COMMAND pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | awk '/version:/ {print $2}'` 
which then runs successfully.

**Comment by wjakob** [comment]
That's an interesting setup -- I was not aware that one could install the command line tools on their own. Unfortunately, the workaround you suggested is not general enough. For example, I often use `xcode-select --switch <XCode folder>` to switch between different XCode versions. The `pkgutil` output remains frozen at whatever was installed through the app store, while `xcodebuild -version` reflects the change. Do you have any other ideas?

**Comment by wjakob** [comment]
nvm, I just nuked the XCode version test altogether: https://github.com/wjakob/nanobind/commit/0859fb2d95096571fc7b4525f44b4f93667149f6

**Comment by brendan-ward** [comment]
Thanks @wjakob for the quick fix!  Apologies for the poor workaround; I'm not at all an expert in correctly identifying XCode versions.

Confirmed that the fix resolved my issue.
