### ISSUE TITLE
How to migrate Eigen from pybind11?

### ISSUE THREAD

**Issue by polortiz4** [wjakob/nanobind#142]
I'm maintaining a library that used pybind11/eigen.h. It appears this header is not in nanobind, but there is the `eigen` directory. How do we port binding code that relied on `eigen.h` to nanobind? 
In particular, this library used `const Eigen::Matrix4f&`

**Comment by wjakob** [comment]
As the issue tracker instructions indicate, please don't use issues to ask questions.
