### ISSUE TITLE
nanobind::tuple default constructor creates a null handle

### ISSUE THREAD

**Issue by stellaraccident** [wjakob/nanobind#241]
When porting some old pybind11 code, I found that `nb::tuple{}` creates a `tuple` class with a nullptr handle, which promptly segfaults if doing anything with it. I feel like in order to be consistent with `list` and `dict`, this should have a default constructor like:

```
tuple() : object(PyTuple_New(0), detail::steal_t()) { }
```

**Comment by wjakob** [comment]
This was fixed here: https://github.com/wjakob/nanobind/commit/506185dca821c9cc1268c33b4cc867ae20f0fc4b
