### ISSUE TITLE
nanobind::enum_ does not have a member function called export_values()

### ISSUE THREAD

**Issue by efifogel** [wjakob/nanobind#27]
### Problem description

I think the title says it all.
While this could be considered as a feature, it would be a bit hard to port binding code from pybind11 (or boost.python) and keep the python code that uses the bindings running.

**Comment by wjakob** [comment]
Hi Efi, as mentioned in the project-specific issue tracker ticket instructions, issues should not be used for feature requests. You are welcome to start a discussion and that will eventually turn into a PR by yourself or somebody else.
