### ISSUE TITLE
[BUG]: Typeid information differs in across shared library causing nanobind to abort

### ISSUE THREAD

**Issue by zhqrbitee** [wjakob/nanobind#283]
### Problem description

Hi,
I have use case that defines a base class in our codebase, e.g.
```c++
// the header file, named as `test.h`
#pragma once

struct Scoreboard {
  Scoreboard() = default;
};
```
```c++
// our nanobind cpp file that is compiled to `base.cpython-39-darwin.so`
#include "test.h"
#include "nanobind/nanobind.h"
namespace nb = nanobind;

NB_MODULE(base, m) {
  nb::class_<Scoreboard>(m, "Scoreboard")
      .def(nanobind::init<>{});
}
```
In user side, they can derived the base class.
```c++
// user's nanobind cpp file that is compiled to `derived.cpython-39-darwin.so`
#include "test.h"
#include "nanobind/nanobind.h"
namespace nb = nanobind;

struct MyScoreboard: public Scoreboard {
  MyScoreboard() = default;
};

NB_MODULE(derived, m) {
  nanobind::module_::import_("base");
  nb::class_<MyScoreboard, Scoreboard>(m, "MyScoreboard")
      .def(nanobind::init<>{});
}
```

When trying to import the derived class `MyScoreboard`:
```python
from derived import MyScoreboard
```
It gives below error (in debug mode): `Critical nanobind error: nanobind::detail::nb_type_new("MyScoreboard"): base type "Scoreboard" not known to nanobind!`. 

The root cause is that the `std::type_info` of `Scoreboard` in two shared libraries are difference and it causes the `nb_type_lookup` function fails. (my environment is M1 (Arm64) with clang, so it is linked with libstdc++ and it seems this is some behavior observed with libstdc++).

After some more search, I found this is actually a issue mentioned in pybind11: https://github.com/pybind/pybind11/issues/912 and the solution is to have custom hash function for `std::type_info`: https://github.com/pybind/pybind11/pull/915/files. The only drawback seems to me is that it could slow things down as we need hashing on string. 

So any plan to port that fix from pybind11 or any other idea to fix this issue?

### Reproducible example code

```text
See the code in problem description
```

**Comment by zhqrbitee** [comment]
Here is a patch I verified that works in my local:
```c++
diff --git a/src/nb_internals.h b/src/nb_internals.h
index a59e43e..462b442 100644
--- a/src/nb_internals.h
+++ b/src/nb_internals.h
@@ -158,7 +158,35 @@ struct nb_weakref_seq {
     nb_weakref_seq *next;
 };
 
+// See https://github.com/pybind/pybind11/issues/912
+// Python loads modules by default with dlopen with the RTLD_LOCAL flag; under libc++ and possibly
+// other stls, this means `typeid(A)` from one module won't equal `typeid(A)` from another module
+// even when `A` is the same, non-hidden-visibility type (e.g. from a common include).  Under
+// stdlibc++, this doesn't happen: equality and the type_index hash are based on the type name,
+// which works.  If not under a known-good stl, provide our own name-based hasher and equality
+// functions that use the type name.
+#if !defined(_LIBCPP_VERSION)
 using nb_type_map = py_map<std::type_index, type_data *>;
+#else
+struct type_hash {
+  NB_INLINE size_t operator()(const std::type_index &t) const {
+    // the djb2 hash algorithm
+    size_t hash = 5381;
+    const char *ptr = t.name();
+    while (auto c = static_cast<unsigned char>(*ptr++)) {
+      hash = (hash * 33) ^ c;
+    }
+    return hash;
+  }
+};
+struct type_equal_to {
+  NB_INLINE bool operator()(const std::type_index &lhs, const std::type_index &rhs) const {
+    return lhs.name() == rhs.name() ||
+        std::strcmp(lhs.name(), rhs.name()) == 0;
+  }
+};
+using nb_type_map = py_map<std::type_index, type_data *, type_hash, type_equal_to>;
+#endif
 
 /// A simple pointer-to-pointer map that is reused a few times below (even if
 /// not 100% ideal) to avoid template code generation bloat.
```

**Comment by wjakob** [comment]
AFAIK, on M1 with `libc++` this issue is solved — indeed, the test suite contains a multi-module example with a shared type and would otherwise fail. You mention `libstdc++`, which is AFAIK not supported on this environment. Can you clarify?

**Comment by zhqrbitee** [comment]
@wjakob 

Thanks for your reply, the `libstdc++` is a typo, I mean `libc++`. 

I follow your suggestion https://nanobind.readthedocs.io/en/latest/faq.html#nanobind-cannot-pass-instances-of-my-type-in-a-multi-library-extension-project and it works in my M1 environment. 

However, I have another environment that uses clang in linux and I cannot make it work even with `__attribute__ ((visibility("default")))`:
```
clang version 15.0.7
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

My simple testbench is attached here: [type_id_issue.zip](https://github.com/wjakob/nanobind/files/12446706/type_id_issue.zip)

I even tried compile with `-rdynamic`, but it does no help. It seems unrelated to nanobind, but any suggestion?

**Comment by wjakob** [comment]
Before making any changes, it would be important to have a CI runner that produces such a failure with the default test suite. Could I ask you to create one?
