### ISSUE TITLE
[BUG]: Building with meson 

### ISSUE THREAD

**Issue by peekxc** [wjakob/nanobind#306]
### Problem description

I tried taking a simple file that used pybind11 bindings and porting it to nanobind, but after it compiled I ran into the error: 

> ImportError: dlopen(< extension module path>.cpython-311-darwin.so, 2): Symbol not found: __ZN8nanobind6detail10module_newEPKcP11PyModuleDef
> ...

Demangling the error says the symbol not found is this: 

> _nanobind::detail::module_new(char const*, PyModuleDef*)

This is likely a result of me trying to using meson-python to compile the extension module. Indeed, I tried to just replicate the [cmake installation steps](https://nanobind.readthedocs.io/en/latest/building.html#finding-nanobind) for my meson.build as follows: 

```meson
py_mod = import('python')
py = py_mod.find_installation(pure: true)
incdir_nanobind = run_command(py, ['-c', 'import os; os.chdir(".."); import nanobind; print(nanobind.include_dir())'], check : true).stdout().strip()
...
inc_nanobind = include_directories(incdir_nanobind)

py.extension_module(
    < extension module >
    include_directories: [inc_nanobind]
    install: true, ...
  )
```

I suspect the linking issue is related to the fact that I'm using meson to build an extension_module instead of using nanobind's cmake-specialized [nanobind_add_module](https://nanobind.readthedocs.io/en/latest/api_cmake.html#command:nanobind_add_module) command; then again, I was able to compile fine with pybind11. 

It there something obvious I'm missing here?

**Comment by wjakob** [comment]
Meson isn't a supported build system of nanobind. If you use something like that, you are unfortunately on your own.

**Comment by peekxc** [comment]
Sounds good. Thanks for the quick response!
