### ISSUE TITLE
[BUG]: std::vector containing non-trivially copyable types are unexpectedly moved

### ISSUE THREAD

**Issue by JasperRobeer** [wjakob/nanobind#307]
### Problem description

We found some unexpected behavior when creating a binding for some types, which are not trivially copyable, and passing them between Python and C++ in lists/vectors using the type casters.

We would expect that objects in the lists/vectors remain unchanged after passing them to functions bound in C++. The Python example below illustrates this.

Inspecting the issue in a debugging session, we see a move constructor being called, but we would expect to see the copy constructor being called.

We have reproduced this issue in version `v.1.5.2`.

### Reproducible example code

```text
//
// C++
//

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>
namespace nb = nanobind;

struct example
{
    std::string text;
};

NB_MODULE(example, m) {
    nb::class_<example>(m, "Example")
        .def(nb::init<const std::string&>())
        .def_rw("text", &example::text)
        .def(
            "__repr__",
            [](const example& e) {
                return std::string("Example(\"") + e.text + "\")";
            }
        );

    m.def(
        "process",
        [](const std::vector<example>& v) {
            return v.size();
        },
        nb::arg("v")
    );
}


#
# Python
#

# To reproduce the issue in Python:
from example import Example, process
a = [Example("A"), Example("B")]
b = process(a)
print(a)

# We expect `a` to be unchanged, but if we inspect it we get:
#   [Example(""), Example("")]
```

**Comment by wjakob** [comment]
This is very bad 😱. I am surprised that this has apparently always been an issue, and that you are the first to stumble into it.  Will have a fix coming up soon (unfortunately a quite intrusive one that changes many things and will need to stay on `master` for 1-2 weeks to stabilize a bit and gather feedback)

**Comment by wjakob** [comment]
Fixed in the `master` branch -- could I ask you to double-check that it addresses your problem?

**Comment by JasperRobeer** [comment]
Yes, the issue appears to be fixed. Thank you very much for your quick resolution!

**Comment by wjakob** [comment]
Great to hear -- I think I will actually push this out fairly soon to get feedback. I think that the current bug is more serious than concerns about keeping compatibility.

**Comment by matthewdcong** [comment]
I just ran into this myself. After updating to the latest, it appears to be fixed.
