### ISSUE TITLE
Typo in the 'Higher order functions' example

### ISSUE THREAD

**Issue by yhirose** [wjakob/nanobind#308]
@nschloe thank you for this useful library. I just tried to compile the 'Higher order functions' example, but I got a build error at the following line.

https://github.com/wjakob/nanobind/blob/b9a2231624e1e2af6f8eaa2e819c2010096a0570/docs/basics.rst?plain=1#L434

After I changed the code from `auto callback = [name = p.name()] {` to `auto callback = [name = p.name] {`, then I now able to compile the line. It's because `Dog::name` isn't a method, but a member variable.

Hope it helps!

**Comment by nschloe** [comment]
@yhirose I just have one commit in this repo. You should thank @wjakob.

**Comment by yhirose** [comment]
@nschloe thanks for catching my mistake... :)
@wjakob thanks a lot for your hard work to make this fantastic library!
