### ISSUE TITLE
NDArray bug with Clang (MinGW)

### ISSUE THREAD

**Issue by a17brah** [wjakob/nanobind#314]
### Problem description

I managed to compile nanobind with Clang (MingW) and linking it against Python 3.11 (MSC).  I noticed that for large tensors I am reading the wrong values with NDArray (and works fine for small tensors). Do you think it's due to an incompatibility between Clang(MinGW) and Python 3.11 (MSC) ?

**Comment by wjakob** [comment]
MingGW is not a supported compiler, so I unfortunately can't help you with this. Can you try to create a reproducer that demonstrates the issue on one of the supported compilers?

**Comment by wjakob** [comment]
(I will close this issue for now, please post a new one if you are able to create a reproducer)
