### ISSUE TITLE
 [feature request]: type caster for c char array[]

### ISSUE THREAD

**Issue by qytz** [wjakob/nanobind#315]
test code:

```
#include <nanobind/nanobind.h>

namespace nb = nanobind;
using namespace nb::literals;

typedef char NameType[16];
struct UserInfo {
  NameType Name;
};

NB_MODULE(test_ext, m) {
  nb::class_<UserInfo>(m, "UserInfo", "test doc")
      .def(nb::init<>())
      .def_rw("Name", &UserInfo::Name, "user name");
}
```

errors when build

> nanobind/include/nanobind/nb_class.h: In instantiation of ‘nanobind::class_<T, Ts>& nanobind::class_<T, Ts>::def_rw(const char*, D C::*, const Extra& ...) [with C = UserInfo; D = char [16]; Extra = {char [10]}; T = UserInfo; Ts = {}]’:
     src/test_ext.cpp:14:14:   required from here
     nanobind/include/nanobind/nb_class.h:530:39: error: invalid array assignment
        530 |             [p](T &c, Q value) { c.*p = (Q) value; },
            |                                  ~~~~~^~~~~~~~~~~
      ninja: build stopped: subcommand failed.

**Comment by wjakob** [comment]
It's not supported, sorry.
