### ISSUE TITLE
clangd: "Too many errors emitted, stopping now"

### ISSUE THREAD

**Issue by tbrekalo** [wjakob/nanobind#316]
# Description

I can successfully compile a project with nanobind but I am getting odd clangd issues as shown in the following screenshot.

![image](https://github.com/wjakob/nanobind/assets/32259102/b71928b3-1056-4ef7-8c55-f7de68255072)

## Setup
```cmake
if(ZEN_BUILD_PYTHON OR SKBUILD)
  if(SKBUILD)
    message(STATUS "Python_VERSION ${PYTHON_VERSION_STRING}")
    message(STATUS "Python_EXECUTABLE ${PYTHON_EXECUTABLE}")
    message(STATUS "Python_INCLUDE_DIR ${PYTHON_INCLUDE_DIR}")
    message(STATUS "Python_LIBRARIES ${PYTHON_LIBRARY}")
    set(Python_VERSION "${PYTHON_VERSION_STRING}")
    set(Python_EXECUTABLE "${PYTHON_EXECUTABLE}")
    set(Python_INCLUDE_DIR "${PYTHON_INCLUDE_DIR}")
    set(Python_LIBRARIES "${PYTHON_LIBRARY}")
  endif()

  find_package(Python 3.8 COMPONENTS Interpreter Development.Module)
  if(ZEN_BUILD_PYTHON)
    message(STATUS "Fetching nanobind")
    include(FetchContent)
    FetchContent_Declare(
      nanobind
      GIT_REPOSITORY https://github.com/wjakob/nanobind.git
      GIT_TAG v1.6.2)

    FetchContent_MakeAvailable(nanobind)
  else()
    execute_process(
      COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
      OUTPUT_STRIP_TRAILING_WHITESPACE
      OUTPUT_VARIABLE NB_DIR)
    list(APPEND CMAKE_PREFIX_PATH "${NB_DIR}")
    # Now import nanobind from CMake
    find_package(nanobind CONFIG REQUIRED)
  endif()

  nanobind_add_module(zen_ext src/bind.cc)
  target_link_libraries(zen_ext PRIVATE zen)

  install(TARGETS zen_ext LIBRARY DESTINATION .)
```

I've tried altering the cmake in few ways but nothing seemed to help.

**Comment by wjakob** [comment]
Two quick comments:
- `FetchContent_*` is not officially supported as a mechanism for embedding nanobind. The two supported ways are: PyPI and as a git submodule.
- I don't use/know clangd and cannot provide support for it. From the quick looks of it, clangd includes nanobind but either cannot find the Python headers or doesn't have C++17 support enabled.

Altogether, this does not strike me as a nanobind issue—it looks to me more like ab issue with your development setup. The issue tracker is reserved for core issues with the library (e.g., if you can share a binding declaration that breaks the library).

**Comment by tbrekalo** [comment]
Thanks for a quick response Wenzel. :)

**Comment by CS-liujf** [comment]
This is due to the c++ standard setting within CMakeLists.txt. It must be designated to c++17 explicitly. Add the following lines
```cmake
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
