### ISSUE TITLE
nanobind vs ctypes

### ISSUE THREAD

**Issue by MohammadRaziei** [wjakob/nanobind#326]
hi. since you provide a comparison of cffi, cython, boost.python, pybind11 and nanobind. but I need a performance or speed benchmark about ctypes. I found numerous new packages that using ctypes. I thought that employing ctypes is a deprecated method. but maybe it has a better performance since many people use it nowadays.

please give your opinion about this and a benchmark for a better comparison.

**Comment by wjakob** [comment]
I don't know and unfortunately don't have time to look into it. If you care strongly about knowing the performance difference, it should be easy for you to do some benchmarking yourself..
