### ISSUE TITLE
[BUG]: Trampoline virtual functions with Eigen::Ref<> as inputs result in compilation errors

### ISSUE THREAD

**Issue by ThoreWietzke** [wjakob/nanobind#330]
### Problem description

Trampoline a virtual function with `Eigen::Ref<>` as an input can't be compiled due to compilation errors. I get two errors inside `nb_call.h`:

> nb_call.h(131,42): error C2039: 'from_cpp': is not a member of 'nanobind::detail::type_caster<Eigen::Ref<Vector,0,Eigen::InnerStride<1>>,int>'

> nb_call.h(99): error C3861: 'from_cpp': identifier not found

A reference implementation without the trampoline and a derived class in c++ works fine and can be compiled.

### Reproducible example code

```text
#include "Eigen/Eigen/Dense"

#include <nanobind/nanobind.h>
#include <nanobind/eigen/dense.h>
#include <nanobind/trampoline.h>

typedef Eigen::Matrix<double, Eigen::Dynamic, 1> Vector;
typedef Eigen::Ref<Vector> VectorRef;

class Base
{
    public:
        ~Base() {};
        virtual double func(VectorRef in) = 0;
};

class PyBase : public Base 
{
    NB_TRAMPOLINE(Base, 1);
    public:

        double func(VectorRef in) override
        {
            NB_OVERRIDE_PURE(
                func, /*Name of function*/
                in /*arguments*/   
            );
        }
};

NB_MODULE(overrideTest, m)
{
    nanobind::class_<Base, PyBase>(m, "Base")
        .def(nanobind::init<>())
        .def("func", &Base::func);
}
```

**Comment by wjakob** [comment]
AFAIK, `Eigen::Ref<>` is a type used to accept inputs, not to return them. The type caster for this type doesn't even have a `from_cpp` method that would be used to convert a C++ type into a Python object. However, when you implement a trampoline, then it's exactly this direction that needs to be available as well. Can you try a map?

**Comment by ThoreWietzke** [comment]
with a `Eigen::Map` the compilation works. 

What I wanted to achieve with the `Eigen::Ref` was a no copy operation between C++ an Python, as the overriden functions in Python are called very often and the output is written in preallocated memory on the C++ side.

**Comment by wjakob** [comment]
Ok. The issue is resolved then, right?

**Comment by ThoreWietzke** [comment]
Not really. I was migrating my codebase from pybind11 to nanobind, and in pybind11 it worked with `Eigen::Ref`

Here is a more brief explanation what I try to do with `Eigen::Ref`: 

I have a C++ function which allocates memory, which shall be filed with a function from a class. An example would be
```cpp
typedef Eigen::Matrix<double, Eigen::Dynamic, 1> Vector;

void foo(Base* base)
{
    double* data = allocateMemory();
    Eigen::Map<Vector> a (data, n)
    base->func(a);

    std::cout << a << std::endl;
}
```
When I inherit from `Base` in Python, I want to modify the passed array in the func() implementation of the Python class. So I need to write inside the allocated memory from the C++ side. I can't change the memory allocation, as this is done in a C library I use.

Is this a bug from your understanding, or shall we move to the diskussion?

**Comment by wjakob** [comment]
To me, it looks more like a feature request: you would like the type caster of `Eigen::Ref` to be more fully featured (currently it does only one direction). Please convert the issue ticket into a discussion post.

I don't use Eigen myself and as such won't have time to work on this. If you or one of the other heavy Eigen users  (@WKarel?) proposes a PR, then it is very likely to b accepted.

**Comment by ThoreWietzke** [comment]
Thanks for your help, I'll open a diskussion post.
