### ISSUE TITLE
CMake configs for using nonobind from C++ projects

### ISSUE THREAD

**Issue by yurybura** [wjakob/nanobind#339]
Since the project provides the ability to develop Python modules in C++, there is a need to connect the library via CMake.
To do this, CMake configs should be generated.

A small example based on C++ and CMake would be helpful:
```cmake
cmake_minimum_required(VERSION 3.15...3.27)
project(example LANGUAGES CXX)

find_package(nanobind REQUIRED)
nanobind_add_module(example example.cpp)
```

**Comment by burgholzer** [comment]
You might be looking for https://github.com/wjakob/nanobind_example

**Comment by wjakob** [comment]
@yurybura There is plenty of documentations about all of this, and an example project as well. The issue tracker of nanobind is reserved for actual bugs. If you have a question, please use the "Discussions" tab.

**Comment by yurybura** [comment]
> You might be looking for https://github.com/wjakob/nanobind_example

Is this example c++ project?

**Comment by yurybura** [comment]
> @yurybura There is plenty of documentations about all of this, and an example project as well. The issue tracker of nanobind is reserved for actual bugs. If you have a question, please use the "Discussions" tab.

This issue is feature request. Should I use Discussions for request new features?

**Comment by wjakob** [comment]
> This issue is a feature request. Should I use Discussions for request new features?

Yes. In fact, the template when opening a new issue explicitly states this (https://github.com/wjakob/nanobind/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml). Did you not see this template when opening this issue?

**Comment by yurybura** [comment]
> > This issue is a feature request. Should I use Discussions for request new features?
> 
> Yes. In fact, the template when opening a new issue explicitly states this (https://github.com/wjakob/nanobind/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml). Did you not see this template when opening this issue?

Github allows to create an issue without a template if it is not suitable. Sorry, I didn't know this policy.
