### ISSUE TITLE
TypeError for ndarray in virtual method of templated class

### ISSUE THREAD

**Issue by silabs-Vladimir** [wjakob/nanobind#344]
Not sure if I am doing anything wrong, but I am getting the following type error:

```
E       TypeError: get_temporary_buffer_size(): incompatible function arguments. The following argument types are supported:
E           1. get_temporary_buffer_size(self, arg: ndarray[dtype=uint8], /) -> int
E       
E       Invoked with types: transforms_ext.CastTransform_uint8_t_int8_t, ndarray
```

The class member function:

```
  virtual size_t get_temporary_buffer_size_binding(nb::ndarray<U> input)
  {
       ...
  }
```
The binding is for the instance where `U=uint8_t`

Called in Python like so:

```
self._impl =  transforms_ext.CastTransform_uint8_t_int8_t(*args) # Call the class constructor
self._impl.get_temporary_buffer_size(x) # x.dtype = np.uint8
```

Been scratching my head about this for a while now, any suggestions what the issue might be?

**Comment by wjakob** [comment]
This is more of a discussion post and not an issue, so I will close your ticket. (Please only submit actual bugs). I think that you might need `nb::ro` for your function to accept read-only arrays.

**Comment by wjakob** [comment]
-> https://nanobind.readthedocs.io/en/latest/ndarray.html#frequently-asked-questions

**Comment by silabs-Vladimir** [comment]
Sorry, but I believe now that this might actually be a bug. The array is writable and the test case for this is not being executed on the Python-side: https://github.com/wjakob/nanobind/blob/master/tests/test_ndarray.cpp#L135

**Comment by silabs-Vladimir** [comment]
For people finding this in the future: 

The issue was that I had not registeret the base class, which is documented here: https://nanobind.readthedocs.io/en/latest/classes.html#subclasses
