### ISSUE TITLE
[BUG]: Cannot reliably use "programmed" name for function name, due to falling out of scope

### ISSUE THREAD

**Issue by chrisrichardson** [wjakob/nanobind#349]
### Problem description

Sometimes it is necessary to create the name of functions and classes during module creation (e.g. for templated classes from C++).
In that case, the `name` attribute (`const char *`) can fall out of scope. The only way around it is to allocate memory, which then causes a memory leak.

In the example below, "mul" is OK, "add" fails when getting `example.add.__name__` in Python, and "sub" is OK, but leaks memory.

### Reproducible example code

```text
#include <nanobind/nanobind.h>
#include <string>

int add(int a, int b) { return a + b; }
int sub(int a, int b) { return a - b; }
int mul(int a, int b) { return a * b; }

NB_MODULE(example, m) {

    m.def("mul", &mul, "Multiply");

    std::string add_name = std::string("add");
    m.def(add_name.c_str(), &add, "Add two integers");

    std::string * sub_name = new std::string("sub");
    m.def(sub_name->c_str(), &sub, "Subtract");
}
```

**Comment by wjakob** [comment]
Tentative fix here (https://github.com/wjakob/nanobind/commit/3c2b64a0ccde7ff09c28dfe20af0d5de96c0f364), can you test if this fixes the issue on your end?

**Comment by chrisrichardson** [comment]
Yes, thanks, that looks good.

**Comment by wjakob** [comment]
Thanks for confirming!
