### ISSUE TITLE
[BUG]: Templated complex functions have issues with  `std::uint32_t`

### ISSUE THREAD

**Issue by jorgensd** [wjakob/nanobind#364]
### Problem description

In FEniCSx, we use templated functions to support both real and complex valued arrays.
We usually pass down numpy arrays with values to C++. 
In some cases, we pass down numpy arrays and unsigned integers in the same function.
A minimal example illustrating a function signature can be found at:
https://github.com/jorgensd/nanobind_example/tree/dokken/nanobind_templating.
In this code, I've created two sets of functions, one that uses a templated function to modify the array, and one where each is hard-coded:
```c++
#include <nanobind/nanobind.h>
#include <nanobind/stl/complex.h>
#include <complex.h>
#include <iostream>
#include <nanobind/ndarray.h>
#include <span>
namespace nb = nanobind;

using namespace nb::literals;

namespace
{
    template <typename T>
    void templated_function(nb::ndarray<T, nb::ndim<1>, nb::c_contig> b, std::uint32_t a)
    {
        std::span<T> c(b.data(), b.size());
        std::for_each(c.begin(), c.end(), [](auto &val)
                      { val *= -2; });
    }
}
NB_MODULE(nanobind_example_ext, m)
{
    m.def(
        "function", [](nb::ndarray<std::complex<double>, nb::ndim<1>, nb::c_contig> b, std::uint32_t a)
        {
        std::cout << "COMPLEX\n";
       std::span<std::complex<double>>c(b.data(), b.size());
        std::for_each(c.begin(), c.end(), [](auto &val)
                      {
            val *= -2; }); },
        "b"_a,
        "a"_a);

    m.def(
        "function", [](nb::ndarray<double, nb::ndim<1>, nb::c_contig> b, std::uint32_t a)
        {
        std::cout << "REAL\n";
        std::span<double>c(b.data(), b.size());
        std::for_each(c.begin(), c.end(), [](auto &val)
                      {
            val *= -2; }); },
        "b"_a,
        "a"_a);

    m.def("new_func", [](nb::ndarray<double, nb::ndim<1>, nb::c_contig> b, std::uint32_t a)
          { templated_function(b, a); });
    m.def("new_func", [](nb::ndarray<std::complex<double>, nb::ndim<1>, nb::c_contig> b, std::uint32_t a)
          { templated_function(b, a); });
}

```
Running this code with the following test suite:
```python
import nanobind_example as m
import numpy as np
import pytest

arr_real = np.array([2.7], dtype=np.float64)
arr_complex = np.array([3+2.8j], dtype=np.complex128)


@pytest.mark.parametrize("func", [m.function, m.new_func])
def test_complex(func):
    a2 = arr_complex.copy()
    func(a2, 2)
    assert np.allclose(a2, -2*arr_complex)


@pytest.mark.parametrize("func", [m.function, m.new_func])
def test_real(func):
    a2 = arr_real.copy()
    func(a2, 2)
    assert np.allclose(a2, -2*arr_real)


@pytest.mark.parametrize("func", [m.function, m.new_func])
def test_complex_uint32(func):
    a2 = arr_complex.copy()
    func(a2, np.uint32(2))
    assert np.allclose(a2, -2*arr_complex)

```
will pass all tests, except the last test `test_complex_uint32` when using the `new_func`. 
One gets the warning
```bash
============================================================================================== warnings summary ===============================================================================================
tests/test_basic.py::test_complex_uint32[new_func]
  /root/shared/tests/test_basic.py:26: ComplexWarning: Casting complex values to real discards the imaginary part
    func(a2, np.uint32(2))
```
which means that the function signature is interpreted as the real valued one, and the input is then copied once it is cast into C++, meaning that we no longer have a view into the data.

**Comment by wjakob** [comment]
You can disable implicit conversions with a `nb::attr("param_name").noconvert()` annotation, which ensures that you always have a read-write view of the data. Sounds like you just want to use this attribute by default. The fact that the implicit conversion tries to throw away the imaginary parts of course isn't nice. 

Does the following patch to nanobind get rid of the warning on your end?

```
diff --git a/src/nb_ndarray.cpp b/src/nb_ndarray.cpp
index b2017fd..6e74699 100644
--- a/src/nb_ndarray.cpp
+++ b/src/nb_ndarray.cpp
@@ -424,9 +424,12 @@ ndarray_handle *ndarray_import(PyObject *o, const ndarray_req *req,
         }
     }
 
+    bool refused_conversion = t.dtype.code == (uint8_t) dlpack::dtype_code::Complex &&
+                              req->dtype.code != (uint8_t) dlpack::dtype_code::Complex;
+
     // Support implicit conversion of 'dtype' and order
     if (pass_device && pass_shape && (!pass_dtype || !pass_order) && convert &&
-        capsule.ptr() != o) {
+        capsule.ptr() != o && !refused_conversion) {
         PyTypeObject *tp = Py_TYPE(o);
         str module_name_o = borrow<str>(handle(tp).attr("__module__"));
         const char *module_name = module_name_o.c_str();
```

**Comment by wjakob** [comment]
Minor: in your reproducer, the `a` and `b` labels are mixed up.

**Comment by jorgensd** [comment]
> Minor: in your reproducer, the `a` and `b` labels are mixed up.

I've corrected the labels in the repo and in the text above.

**Comment by jorgensd** [comment]
> You can disable implicit conversions with a `nb::attr("param_name").noconvert()` annotation, which ensures that you always have a read-write view of the data. Sounds like you just want to use this attribute by default. The fact that the implicit conversion tries to throw away the imaginary parts of course isn't nice.
> 
> Does the following patch to nanobind get rid of the warning on your end?
> 

I can confirm that this fixes the issue. 
@mscroggs can you test this with your example as well?:)

**Comment by wjakob** [comment]
The patch, or the `.noconvert()` annotation?

**Comment by jorgensd** [comment]
> The patch, or the `.noconvert()` annotation?

The patch.

**Comment by wjakob** [comment]
Fixed, thanks for the report.
