### ISSUE TITLE
[BUG]: Returns wrong values on first call

### ISSUE THREAD

**Issue by weshoke** [wjakob/nanobind#371]
### Problem description

The function returns all zeros and then the proper values on subsequent calls

### Reproducible example code

```text
m.def("test2", []() {
    std::vector<float> parameter;
    parameter.emplace_back(1.0);
    parameter.emplace_back(2.0);
    parameter.emplace_back(3.0);
    return nb::ndarray<nb::numpy, Scalar, nb::c_contig, nb::device::cpu,
                       nb::ndim<1>>(parameter.data(), {parameter.size()});
  });


print(pybvh.test2())
print(pybvh.test2())
print(pybvh.test2())
```

**Comment by weshoke** [comment]
Output is:

```
[0. 0. 0.]
[1. 2. 3.]
[1. 2. 3.]
```

**Comment by wjakob** [comment]
This is undefined behavior on your end and not a nanobind bug. Who owns your `std::vector` after the function returns? Please carefully read the nanobind documentation before posting issues. It specifically discusses such questions of ownership (in general, and specifically for ndarrays).
