### ISSUE TITLE
[BUG]: Returning an `enum` with `def_property_readonly` gives strange results

### ISSUE THREAD

**Issue by chrisrichardson** [wjakob/nanobind#39]
### Problem description

When returning an `enum` with `def_property_readonly`, the wrong value is sometimes returned.
I have this problem in a larger wrapper code, but tried to reproduce here as a minimal example in a test.

In the code below, both `get_enum()` and `read_enum` should return `Enum.A`, however `read_enum` returns `Enum.B` apparently.
What is also strange is that `e2` below compares as equal to `t.Enum.A` although it prints as `t.Enum.B`.

### Reproducible example code

```text
// C++ code

  class EnumHolder {
  public:
    EnumHolder() {}
    Enum get_enum() { return Enum::A; }
  };

  nb::class_<EnumHolder>(m, "EnumHolder")
      .def(nb::init<>())
      .def("get_enum", &EnumHolder::get_enum)
      .def_property_readonly("read_enum", &EnumHolder::get_enum);

# Python code
def test05_enum_property():
    w = t.EnumHolder()
    e1 = w.get_enum()
    e2 = w.read_enum
    print(e1, e2)
    assert e1 == t.Enum.A
    assert e2 == t.Enum.B
```

**Comment by chrisrichardson** [comment]
I guess this is because `def_property_readonly` expects a const reference, and not a return by value? So maybe user error...?

**Comment by wjakob** [comment]
This looks like a bug to me, you aren't doing anything unsupported.

Could you give this a try with the latest version of nanobind (git, master branch)? The enum support had a number of changes in the last few days. The testcase you posted passes on my computer.

**Comment by wjakob** [comment]
(nevermind, I see now that there is some kind of issue)

**Comment by wjakob** [comment]
Fixed in master.
