### ISSUE TITLE
[BUG]: CMake Error -- Target "nanobind-static" links to: Python::Module but the target was not found.

### ISSUE THREAD

**Issue by ftpronk** [wjakob/nanobind#398]
### Problem description

On **Windows**, the `CMake` configuration step fails when the Python environment has been searched for using the `FindPython3` module with the code `find_package(Python3 ...)`.

The following changes bypass/solve the issue: 
 - searching for the Python environment with the `FindPython` module: `find_package(Python ...)`
 - modifying the `Python::Module` calls to `Python3::Module` in `cmake/nanobind-config.cmake`  

It would be nice if the nanobind CMake configuration would also work with the `FindPython3` CMake module. 

Minimal system packages:
- MSVC 2022 compiler
- CMake 3.28.1
- Python 3.12
 

### Reproducible example code

```text
find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
[...]
nanobind_add_module(pylib ${pylib_SOURCES})
```

**Comment by wjakob** [comment]
``FindPython3`` is not supported, please use ``FindPython``.

**Comment by ftpronk** [comment]
As this is your library, you can do as you please.

But as `FindPython3` is an official and legitimate CMake module to find Python, maybe a note in the documentation mentioning that it is not support could be helpful?
