### ISSUE TITLE
Installation from tar file fails on submodule

### ISSUE THREAD

**Issue by VictorEijkhout** [wjakob/nanobind#403]
### Problem description

I downloaded the 1.8.0 tgz file. Running cmake tells me:
```
CMake Error at CMakeLists.txt:34 (message):
  The nanobind dependencies are missing! You probably did not clone the
  project with --recursive.  It is possible to recover by invoking

  $ git submodule update --init --recursive
```
Of course doing `git submodule` fails because it's not a repository.

Do I conclude that installing from tarfile is basically not possible?

**Comment by wjakob** [comment]
Yes, you conclude correctly. Unfortunately it's not possible to include the other repository since GitHub makes those tarballs without our control. The fix would be easy by also downloading the tarball of the robin_map project and extracting it there.
