### ISSUE TITLE
[OTHER]:  external  robin-map support

### ISSUE THREAD

**Issue by blshkv** [wjakob/nanobind#410]
### Please support a system-wide installed software

robin-map is an independent software (just .h headers, but still) which could be installed separately.
Please unbundle it from nanobind or add an option ```EXTERNAL_ROBINMAP``` and ```find_package(tsl-robin-map)``` in the CMakeLists.txt file. FYI, the default location is ```/usr/share/cmake/tsl-robin-map```

**Comment by wjakob** [comment]
AFAIK there is already such a feature (search for `NB_USE_SUBMODULE_DEPS`). If that doesn't solve your issue, you are welcome to propose PR with fixes.

**Comment by blshkv** [comment]
Thank you for pointing it out, and also documenting it in a4ccea860af5943fd0d68cdd327f277ef31c5e05
I believe this feature is not yet available in 1.8.0, so I'm looking forward to a new release.
