### ISSUE TITLE
[BUG]: Linker Error when trying to build with Visual Studio.

### ISSUE THREAD

**Issue by tomgwasira** [wjakob/nanobind#415]
### Problem description

Hi. Thank you for this library.

I am trying to use it with Visual Studio and have followed the instructions for use of Pybind11 with Visual Studio detailed [here](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022). It builds successfully with Pybind11.

However, I when I follow the exact same instruction for Nanobind, with the exception of using `python -m nanobind --include_dir` to get the nanobind include directory, I get the linker errors shown below.
![image](https://github.com/wjakob/nanobind/assets/47949506/020e8cb1-c9ce-4368-8e9f-0a1e14c386cf)

I don't know if there is something I am missing. Looking forward to your response.

**Comment by wjakob** [comment]
This is highly unlikely to be a nanobind bug and rather some way in which you deviate from the official build system/instructions. One reference point is that both CI & the example project build without issues on visual studio.  I suggest that you carefully look at them to find the point of deviation.

**Comment by tomgwasira** [comment]
Thanks @wjakob for the response. Will keep at it and report back on what the issue was.
