### ISSUE TITLE
[OTHER]: Nanobind for python3.9 - python39.lib and and python.h are not recongnized

### ISSUE THREAD

**Issue by petrasvestartas** [wjakob/nanobind#419]
### Please don't use.

Hi,

I have been using **Nanobind** and **Pybind11** with **Anaconda** that builds without issues using **setup.py** file where I link C++ files and libraries.

Now I have situation where I need to compile **python / c++** code of **Nanobind** in a **python3.9** in a **3rd party software** that has its **own python environment** (not anaconda, packages are installed only through **pip**). Normally I can install my python packages there using `pip install -e .` But for compiling Nanobind it does not find `Python.h` and `python39.lib` files. I searched the folder of this environment and it does not have `Python.h` and `python39.lib` files. 

What would be a correct way to link these files?

This python configuration is part of Rhino3D software, but for sure the developer is silent as a stone...

<img width="517" alt="image" src="https://github.com/wjakob/nanobind/assets/18013985/37eea838-24e5-4ea1-9ee9-d96d38fd5c35">

My setup file incase needed looks like this:

**Comment by wjakob** [comment]
This is not a nanobind issue. It sounds to me like something that is highly specific to your setup and is unfortunately beyond the scope of this support channel.
