### ISSUE TITLE
[BUG]: Cannot resolve numpy array as tensor input if flag `write=False` is set

### ISSUE THREAD

**Issue by chrisrichardson** [wjakob/nanobind#42]
### Problem description

If we have a function which takes a const reference, it should be possible to do something like this:

`m.def("get_dim", [](const nb::tensor<const double>& x){ return x.ndim(); });`

and send in an unwriteable numpy array:

```
    w = np.array([[2.0,2.0]])
    w.setflags(write=False)
    assert (module.get_dim(w) == 2)
```

But this doesn't seem to work at the moment:
```
E       TypeError: get_dim(): incompatible function arguments. The following argument types are supported:
E           1. get_dim(arg: tensor[dtype=float64], /) -> int
E       
E       Invoked with types: ndarray
```

Removing the `write=False`, it works fine, but sometimes we have an unwriteable array from somewhere else...

**Comment by brettc** [comment]
I think I have the same problem. I'm converting code from pybind11, and I pass in a numpy array which is constructed from a buffer:

```python
buf = fstream.read(RAW_CHUNK_SIZE)
arr = np.frombuffer(buf, dtype=np.int8)
```
Passing `arr` into a function with just `nb::tensor<>` as the parameter gives me the same error as above, I'm guessing because `frombuffer` makes it not writeable.

**Comment by brettc** [comment]
I spent a bit of time futzing around trying to debug this. 

https://github.com/wjakob/nanobind/blob/8555cf8d22336fc0008c4a21fe708723ad0a4721/src/tensor.cpp#L152

  if (PyObject_GetBuffer(o, view.get(), PyBUF_RECORDS)) {

**Comment by brettc** [comment]
It appears the readonly problem is not just with nanobind.

```python
import numpy as np
w = np.array([[2.0,2.0]])
w.setflags(write=False)
w.__dlpack__()
```
gives
```
TypeError: NumPy currently only supports dlpack for writeable arrays
```

Some discussion here: https://github.com/numpy/numpy/issues/20742

So is the issue that dlpack doesn't support readonly buffers?

**Comment by whateverforever** [comment]
Relevant when working with [mikedh/trimesh](https://github.com/mikedh/trimesh), as the vertex and normal arrays have write=False by default

**Comment by wjakob** [comment]
I will close this issue, the current `master` version of nanobind addresses it to my knowledge. If not, feel free to reopen.
