### ISSUE TITLE
[BUG]:  device::cuda with jax array create array on cpu

### ISSUE THREAD

**Issue by dingjr7** [wjakob/nanobind#422]
### Problem description

When creating jax array with device::cuda tag, the created array in python is still on cpu.

### Reproducible example code

```text
struct A {
    using T = nb::ndarray<nb::jax, float, nb::device::cuda>;
    T a;

    A(std::vector<size_t> shape) {
        size_t i = 1;
        for (auto size : shape) {
            i *= size;
        }
        // float *buffer;
        // cudaMalloc(&buffer, sizeof(float) * i);
        float *buffer = (float *)malloc(sizeof(float) * i);
        a = T(buffer, shape.size(), shape.data());
    }
};

nb::class_<A>(m, "A")
        .def(nb::init<std::vector<size_t>>())
        .def_rw("a", &A::a);
```

**Comment by wjakob** [comment]
nanobind isn't responsible for moving data to the GPU -- it does not know about CUDA, ROcm, or any other framework. It is your responsibility to provide a pointer in the right address space.

**Comment by wjakob** [comment]
(Please open a discussion next time -- this isn't a bug with nanobind, and the issue tracker reserved for things that are clearly and obviously bugs)

**Comment by dingjr7** [comment]
I mean if i allocate memory on gpu as the commented lines do, the python program will core dumped. I checked the jax array in python, it says CPUdevice. I think it is a bug.

**Comment by dingjr7** [comment]
![image](https://github.com/wjakob/nanobind/assets/67504459/3f39bfd2-24bf-4c36-8731-edeccbd7b204)
In addressabe_shards we saw device=CPUdevice
