### ISSUE TITLE
[BUG]: Last commit broke something: No such file or directory #include<nanobind/nanobind.h>

### ISSUE THREAD

**Issue by a-mruiz** [wjakob/nanobind#425]
### Problem description

I had two projects up and running with Nanobind, up until yesterday everything was working (I've tested 8 hours ago).
Today the pip install . cannot find the nanobind, this happend in both projects without changing anything CMake related, just wanted to let you know

**Comment by a-mruiz** [comment]
I'm on 1.9.1 (checked the __init__ inisde src folder) and no luck :(

**Comment by wjakob** [comment]
Can you try again with 1.9.2 I release just now?

**Comment by torokati44** [comment]
Should the diff between `1.9.1` and `1.9.2` be indeed nothing more than a patch version bump? :thinking:

**Comment by a-mruiz** [comment]
@wjakob 1.9.2 Fixes it! Thank you so much for the prompt response and fix! Keep up this amazing project :)

**Comment by wjakob** [comment]
@torokati44 yes, because I made a bad wheel that was missing some files. And you cannot re-release the same version with fixes on PyPI.

**Comment by torokati44** [comment]
Ah, okay, I see.
