### ISSUE TITLE
[BUG]: Test Case test_classes.py Failed

### ISSUE THREAD

**Issue by lyd405121** [wjakob/nanobind#429]
## Problem
-  After Compile nanobind successfully
- I run test_classes.py with “Python 3.10.11” in windows10
- Here is the error report
![error](https://github.com/wjakob/nanobind/assets/16344694/0ea167cf-fded-42a3-a314-67adff6a7ade)
- While other test cases have passed

## Solve
- I just modify "is" to "==", it works well
![right](https://github.com/wjakob/nanobind/assets/16344694/9b47a6f1-3296-467c-9eaf-ce0a36b5569d)
- Is that right  and should I make a pr ?

**Comment by wjakob** [comment]
Thanks for the report! This is not how you run the test suite, by the way. You will need to call PyTest.
