### ISSUE TITLE
[BUG]: Compiling nanobind master branch on musllinux result in `error: 'nullptr_t' has not been declared`

### ISSUE THREAD

**Issue by laggykiller** [wjakob/nanobind#430]
### Problem description

Compiling nanobind master branch on musllinux result in `error: 'nullptr_t' has not been declared`. This seems to be a regression.

Github action log: https://github.com/laggykiller/apngasm-python/actions/runs/8060668383/job/22017067643#step:4:4735

**Comment by laggykiller** [comment]
Done git bisect, b3c483edbfe729c1064c3ec1758de3c8ff0ad458 is the first bad commit

**Comment by wjakob** [comment]
Thanks!

**Comment by laggykiller** [comment]
It's not solved yet: https://github.com/laggykiller/apngasm-python/actions/runs/8063189658/job/22024496317#step:4:1

**Comment by wjakob** [comment]
oops, try again please.

**Comment by laggykiller** [comment]
Can confirm that it is properly fixed, thanks!
