### ISSUE TITLE
[OTHER]: How to deal with the potential “wild pointer" when using the exposed vector?

### ISSUE THREAD

**Issue by Yikai-Liao** [wjakob/nanobind#431]
The problem is simple. When we free a vector (e.g., by replacing it with another vector), python objects that refer to elements in that vector become "wild pointers".

I verified my suspicions with the following code. I'd like to know if there's a way to avoid this problem, or at the very least get a warning when I access invalid python objects, because accessing these "wild pointers" has a probability of giving the program a segmentation fault.

Here is the minimal code:

```c++
#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>
#include <nanobind/stl/bind_vector.h>
#include <vector>
#include <string>
namespace nb = nanobind;

struct Bar {
    int data;
    explicit Bar (const int data) : data(data) {}
};

struct Foo {
    std::vector<Bar> bars;
    explicit Foo(std::vector<Bar> bars) : bars(std::move(bars)) {}
};



NB_MAKE_OPAQUE(std::vector<Bar>);

NB_MODULE(nanobind_example_ext, m) {
    nb::class_<Bar>(m, "Bar")
        .def(nb::init<int>())
        .def_rw("data", &Bar::data)
        .def("__repr__", [](const Bar& self) { return "Bar(" + std::to_string(self.data) + ")"; });

    nb::bind_vector<std::vector<Bar>>(m, "BarList");

    nb::class_<Foo>(m, "Foo")
        .def(nb::init<std::vector<Bar>>())
        .def_rw("bars", &Foo::bars)
        .def("__repr__", [](const Foo& self) { return "Foo(" + std::to_string(self.bars.size()) + " bars)"; });
}
```
```python
# in ipython
from nanobind_example.nanobind_example_ext import Foo, Bar, BarList
f = Foo(BarList([Bar(i) for i in range(10000)]))
b = f.bars[-1]
print(b, id(b)


%%timeit
f.bars = BarList(Bar(0) for _ in range(10000))


print(b, id(b)
```

![image](https://github.com/wjakob/nanobind_example/assets/110762732/4cc916f7-0576-4976-8033-ba41c7233bad)

**Comment by wjakob** [comment]
I didn't have time to look at this yet -- why did you close the issue? Was it a bug on your end and not in nanobind?

**Comment by Yikai-Liao** [comment]
Oh, I thought it should be in the discussion, as this seems not a bug.
Here is it: https://github.com/wjakob/nanobind/discussions/432.

**Comment by wjakob** [comment]
ah, got it!

**Comment by Yikai-Liao** [comment]
It would be great if you could give some advice as I am really stuck with this problem. It does present a potential wild pointer problem.
