### ISSUE TITLE
[OTHER]: Pointer type usage like: ①pointer to pointer ② reference of pointer

### ISSUE THREAD

**Issue by lyd405121** [wjakob/nanobind#446]
## Background
- Recently，I build a reflect system for C++
- Using Clang to parse *.h files and automaticlly output [rttr](https://github.com/rttrorg/rttr) code 
- And I suddenly came up an idea: **Can I using that system to produce python glue code with nanobind**
- Input any *.h and output nanobind extension automaticly was my ambition！
## Question
- It is very easy to achieve that when the input includes only data oriented struct
- When it turns to interface layer, it's really hard to deal with **double pointer** and **reference of pointer**
![PoiterTestCode](https://github.com/wjakob/nanobind/assets/16344694/b569c10e-6d7a-490f-b8f6-769d83067f00)
- nanobind can't work with double pointer(**Test4**) and reference of pointer(**Test3**), so I use lambda function instead
- Which successfully compiled and my python code below also print the address of the pointer  
![PoiterTestPy](https://github.com/wjakob/nanobind/assets/16344694/a806b459-357e-43d9-b9d2-7506bb377fb0)
- But which confuse me is some addtional print info :
![PoiterTestRet](https://github.com/wjakob/nanobind/assets/16344694/dfb30528-3729-4951-8e22-9b0bf3d43733)

### Question 1 : Two address
- Why there are two address for the variant “value=-1”: 7db25ef1d4 and 7db25ef1f4
- Why the distance between the two address is 32 

### Question 2 : Python value can't be modified
- The variant "value = -1" never changed  even I use its pointer to modify

## Guess
- nanobind store parameter list of a function globally, and my code modify the data in nanobind not the python variant
- I hope my Chinglish has not affected your reading T_T, I just want to figure out nanobind's strategy for pointer

**Comment by wjakob** [comment]
Please don't file issues for things that aren't bugs in the library. I will move this to the discussion page. This kind of nonstandard use case is beyond the set of things for which I can provide support, but perhaps others have ideas.
