### ISSUE TITLE
[BUG]: Build fails with MinGW

### ISSUE THREAD

**Issue by MrAwesomeRocks** [wjakob/nanobind#47]
### Problem description

`std::exception` isn't exported but the subclasses in the library are, causing this compilation error:

```
'dllexport' implies default visibility, but 'class nanobind::index_error' has already been declared with a different visibility
```

This was fixed in PyBind11 with this commit: https://github.com/pybind/pybind11/pull/3132/files

**Comment by wjakob** [comment]
Hi -- this project only targets a few specific compilers (GCC, Clang, and MSVC to be specific). pybind11 ended up in a situation that needed tons of patches in many places to work around miscompilations and other compiler issues in NVCC, MinGW, intel compilers, and many others, which is something I would like to avoid to keep things simple and maintainable.
