### ISSUE TITLE
[BUG]: Complex type does not work in variant

### ISSUE THREAD

**Issue by awni** [wjakob/nanobind#479]
### Problem description

If `std::complex<float>` is included in a variant then it causes the variant to improperly detect non complex types as complex (see example below).

### Reproducible example code

```c++
#include <iostream>
#include <nanobind/nanobind.h>                                                 
#include <nanobind/stl/complex.h>                                              
#include <nanobind/stl/variant.h>                                              

namespace nb = nanobind;                                                       

using MyType = std::variant<
    nb::float_,
    std::complex<float>>;

void print_type(MyType v) {
  if (auto pv = std::get_if<std::complex<float>>(&v); pv) {                    
    std::cout << "GOT COMPLEX " << std::endl;                                  
  } else if (auto pv = std::get_if<nb::float_>(&v); pv) {                      
    std::cout << "GOT FLOAT" << std::endl;                                     
  }                                                                            
}

NB_MODULE(test, m) {
    m.def("print_type", &print_type);                                          
}
```

And in Python:

```python
import test

# Correctly routes to float
test.print_type(1.0)

# Incorrectly routes to cmplex
test.print_type(list())
```

**Comment by awni** [comment]
Thanks for the fix @yosh-matsuda !

**Comment by awni** [comment]
@yosh-matsuda and @wjakob there still seems to be an issue here. In the example above if I send in a NumPy array it matches to complex:

```
import numpy as np
test.print_type(np.array(1.0))
```

Do you mind to reopen this or shall I file a separate bug report?

**Comment by yosh-matsuda** [comment]
@awni I think this is expected behavior.

Roughly speaking, the casting in your case seems to be attempted by the following:

* Casting to `nb::float_` checks `type(numpy.array(1.0)) is float`. => `False`
* Casting to `std::complex<float>` checks,
  1. `type(numpy.array(1.0)) is complex`. => `False`
  2. `type(complex(float(numpy.array(1.0)))) is complex`. => `True`

**Comment by yosh-matsuda** [comment]
How about using `float` instead of `nb::float_`?

```cpp
using MyType = std::variant<
    float,
    std::complex<float>>;
```

**Comment by awni** [comment]
I see, thanks. What I actually want is a third option in the variant to match which is for `nb::ndarray<>`. I supposed if I check for that first, it will catch this case. Let me try.

**Comment by awni** [comment]
PS what works for me is to put the ndarray before the `std::complex<float>` in the variant. Thanks for your help!
