### ISSUE TITLE
[BUG]: Does not seem to complete the build process with the ninja generator

### ISSUE THREAD

**Issue by lpapp** [wjakob/nanobind#48]
### Problem description

The configuration step succeeds, but the subsequent build step fails. It looks like the tests step on each other.

### Reproducible example code

```text
cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -Bbuild/x64-Release .
cmake --build ./build/x64-Release                  
ninja: error: build.ninja:520: multiple rules generate tests/libnanobind.dylib [-w dupbuild=err]
```

I am on a MacBook Pro 2019, Monterey 12.4 if that is any helpful.

**Comment by wjakob** [comment]
Fixed, thanks.
