### ISSUE TITLE
[BUG]: nb::arg("name").sig("sig") doesn't work

### ISSUE THREAD

**Issue by a603032070** [wjakob/nanobind#494]
### Problem description

After compiling the example code, the type annotation for param `name` in the generated stub won't change, though `.sig("sig")` is invoked.
```
# my_ext.pyi
def add(name: int) -> int: ...
```

### Reproducible example code

```text
#include <nanobind/nanobind.h>
namespace nb = nanobind;
int add(int a) { return a; }
NB_MODULE(my_ext, m) { m.def("add", &add, nb::arg("name").sig("sig")); }
```

**Comment by wjakob** [comment]
The `.sig()` part is for overriding how a default argument value is rendered. Your function doesn't have a default argument, hence this annotation does not do anything.

**Comment by a603032070** [comment]
Thanks for your reply. I've noticed that the "default arg" requirement is clear in the related paragraph of the documentation.
However, I think the api itself could be a little bit misleading.
Would it be better if some constraints were imposed on the usage of `.sig`?
e.g. Make the `.sig` a method of nb::arg_v but not nb::arg, and use `.sig` like
`("value"_a = SomeType(123)).sig("SomeType(123)")`
Just an advice.

**Comment by wjakob** [comment]
This is an open source project. I can't guarantee that it would be accepted, but I would be happy to review PRs changing the behavior here.
