### ISSUE TITLE
[BUG]: object won't be released until exit python

### ISSUE THREAD

**Issue by Yikai-Liao** [wjakob/nanobind#505]
### Problem description

![image](https://github.com/wjakob/nanobind/assets/110762732/e367e4ca-639d-441f-a673-197b2e2a1c70)

@wjakob Hi, sorry to bother you, but I found a possible memory leak.

If I create a `c++` struct using`nanobind` and don't assign it to a variable in python, the object won't be freed until I exit `ipython`, even if I manually call `gc.collect()`

### Reproducible example code

```c++
#include <iostream>
#include <nanobind/nanobind.h>

struct Foo {
    int data;
    explicit Foo(int data) : data(data) {}
    ~Foo() {
        std::cout << "Foo " << data << " is destructed" << std::endl;
    }
};

namespace nb = nanobind;


NB_MODULE(core, m) {
    nb::class_<Foo>(m, "Foo")
        .def(nb::init<int>());
}
```

**Comment by hpkfft** [comment]
I believe that `Foo(2)` is kept alive because it is referenced by `_`.
```
>>> Foo(2)
<core.Foo object at 0x7fa465ac9ed0>
>>> _
<core.Foo object at 0x7fa465ac9ed0>
>>> 7
Foo 2 is destructed
7
>>>
```

**Comment by Yikai-Liao** [comment]
So it's a Python syntax feature is it?

**Comment by Yikai-Liao** [comment]
@hpkfft similar issue is also found in vector (using `nb::bind_vector`). But in this case, even if I `del` the vector object manually, it won't be freed until exit. 

I'm not sure exactly what causes this, but this should be a different cause than the previous problem

```c++
#include <iostream>
#include <nanobind/nanobind.h>
#include <nanobind/stl/bind_vector.h>
#include <nanobind/stl/string.h>

struct Foo {
    int data;
    explicit Foo(int data) : data(data) {}
    ~Foo() {
        std::cout << "Foo " << data << " is destructed" << std::endl;
    }
};

namespace nb = nanobind;

NB_MAKE_OPAQUE(std::vector<Foo>);

NB_MODULE(core, m) {
    nb::class_<Foo>(m, "Foo")
        .def(nb::init<int>())
        .def("__repr__", [](const Foo &self) { return "Foo(" + std::to_string(self.data) + ")"; });

    m.def("foos", []() {
        return std::vector<Foo>{Foo(1), Foo(2), Foo(3)};
    });
}
```

![image](https://github.com/wjakob/nanobind/assets/110762732/bdfffd68-aba5-47aa-82ad-4b3749b916cc)

**Comment by bjodah** [comment]
@Yikai-Liao just FYI, you can [configure](https://ipython.readthedocs.io/en/8.23.0/config/options/terminal.html#configtrait-InteractiveShell.cache_size) your `.ipython/profile_default` to contain the line:
```python
c.InteractiveShell.cache_size = 0
```
That disables IPython from hanging on to the output.

**Comment by wjakob** [comment]
This isn't a nanobind bug, I will close this ticket.
