### ISSUE TITLE
[Request]:  stl vector.reserve(...) method

### ISSUE THREAD

**Issue by petrasvestartas** [wjakob/nanobind#527]
Hi,

I would like to ask to implement a "reserve" method for vector binding to allocate memory for adding elements instead of resizing multiple times... I saw it is possible by implementing your own custom vector.
This would same a lot of time specially for large vectors.

Usage:
```python
vector = m.vector1()
vector.reseve(len(python_list))
for i in python_list:
   vector.append(i)
```

You would say that you can directly do this: `vector =  m.vector1(python_list)`, this **wont work** when python_list are not numbers but **custom class instances** :

```python
polyline = m.point1()
for coordinate_list in vectors:
   polyline.append(m.point(*coordinate_list))
   return polyline
```

and no I cannot use **ndarray** or **eigen** because it is a vector of vectors wrapped in a recursive function:
```python
def to_point(vectors, depth):
    if depth == 1:  # Single polyline
        polyline = m.point1()
        for coordinate_list in vectors:
            polyline.append(m.point(*coordinate_list))
        return polyline
    else:  # Nested polyline
        vector = getattr(m, f'vector{depth}')()
        for vec in vectors:
            vector.append(to_vector(vec, depth - 1))
        return vector

def to_point1(polylines):
    return to_point(polylines, 1)

def to_point2(polylines):
    return to_point(polylines, 2)

def to_point3(polylines):
    return to_point(polylines, 3)

def to_point4(polylines):
    return to_point(polylines, 4)
```

C++ binding:

```cpp
    /////////////////////////////////////////////////////////////////////////////////////////////////
    // Types - point
    /////////////////////////////////////////////////////////////////////////////////////////////////
    nb::class_<IK::Point_3>(m, "point")
    .def(nb::init<double, double, double>())
    .def("x", &IK::Point_3::x)
    .def("y", &IK::Point_3::y)
    .def("z", &IK::Point_3::z)
    .def("__getitem__", [](const IK::Point_3& p, size_t i) {
    if (i == 0) return p.x();
    if (i == 1) return p.y();
    if (i == 2) return p.z();
    throw std::out_of_range("Index should be 0, 1, or 2 for x, y, z respectively");})
    ;

    nb::bind_vector<std::vector<IK::Point_3>>(m, "point1");
    nb::bind_vector<std::vector<std::vector<IK::Point_3>>>(m, "point2");
    nb::bind_vector<std::vector<std::vector<std::vector<IK::Point_3>>>>(m, "point3");
    nb::bind_vector<std::vector<std::vector<std::vector<std::vector<IK::Point_3>>>>>(m, "point4");
```

Currently vector bindings are thes which is not complete:
`['Iterator', '__bool__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'count', 'extend', 'insert', 'pop', 'remove']`

**Comment by wjakob** [comment]
The STL vector bindings try to match the Python `list` API, not the `std::vector` one. You can easily add extra methods on your end -- this isn't a change that _needs_ to be in nanobind. (This is a "nano" library, so many feature requests of this type are expected to be declined).
