### ISSUE TITLE
[BUG]: No install target

### ISSUE THREAD

**Issue by lpapp** [wjakob/nanobind#54]
### Problem description

I wrote a conan recipe for nano bind as we would like to use this in our project. But I am getting an error there because nano bind does not offer an install target. This is ideally needed to avoid having to embed nano bind and keep it a separate project.

Would it be possible add an install target to install your files? Thanks.

pybind11 also has an install target.

**Comment by wjakob** [comment]
External contributions to add such an `install` target are welcomed, but I won't be working on it myself (`pip` is the recommended way to install this package). The thing to watch out for is that the install target doesn't interfere with the scikit-build based mechanism for PyPI package generation (it might try to call that, causing duplicated files to show up.. not sure.)
