### ISSUE TITLE
[Feature request]: pdm backend support 

### ISSUE THREAD

**Issue by pythonmobile** [wjakob/nanobind#552]
### Please don't use.

In my current project, this works without issues:

[build-system]
requires = ["nanobind >=1.3.2", "scikit-build-core >=0.4.3"]
build-backend = "scikit_build_core.build"

but the following fails with pdm tests not finding Modules.

 [build-system]
 requires = ["pdm-backend", "nanobind >=1.9.2", "scikit-build-core >=0.9.2"]
 build-backend = "pdm.backend"

Perhaps someone here knows how to fix this?

**Comment by wjakob** [comment]
PDM isn't a supported build backend. Issue tracker tickets aren't meant to be used for feature requests.
