### ISSUE TITLE
[BUG]: visibility attribute gcc on windows (mingw64)

### ISSUE THREAD

**Issue by lkeegan** [wjakob/nanobind#558]
### Problem description

Building nanobind_example with gcc on Windows (mingw64) gives many warnings of the form ([ci example](https://github.com/lkeegan/nanobind_example/actions/runs/8923853927/job/24508966236#step:6:46))

`warning: visibility attribute not supported in this configuration; ignored [-Wattributes]`

As well as these warnings, a real project of mine also gives an import error at runtime:

`ImportError: dynamic module does not define module export function (PyInit_sme)`

## Proposed solution

- use `dllimport` / `dllexport` for visibility on windows (as was previously the case)
  - as documented here: https://gcc.gnu.org/wiki/Visibility#How_to_use_the_new_C.2B-.2B-_visibility_support
  - this reverts the change made in #440
- don't set the `visibility("hidden")` attribute for namespaces on windows
  - this is not supported on windows
  - similar issue here: https://github.com/fmtlib/fmt/issues/1743
  - this resolves the original mingw64 compilation error motivating #440

This is done in #555 which fixes both the compilation warnings seen in nanobind_example ([ci example](https://github.com/lkeegan/nanobind_example/actions/runs/8923868987/job/24509012814#step:6:38)) as well as my ImportError issue in a real project.

Apologies for taking your time for a compiler you explicitly don't support - but hopefully this change is small and generic enough to be worth making. Many thanks for sharing this library!

**Comment by wjakob** [comment]
closed via #555
