### ISSUE TITLE
[OTHER]: Fully formed pyproject.toml request

### ISSUE THREAD

**Issue by pythonmobile** [wjakob/nanobind#563]
### Supporting a fully formed pyproject.toml

Can we get a [project] heading in pyproject.toml please: 

```
[project]
name = "nanobind"
dynamic = ["version", "description", "authors", "license", "homepage", "classifiers"]
```

Once we do this, pdm backend becomes possible to use as well:

```
[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.17", "ninja", "typing_extensions", "pdm-pep517", "pdm-backend"]
build-backend = "pdm.backend"
```

**Comment by wjakob** [comment]
Done in ed5cfd5.

**Comment by wjakob** [comment]
This change broke `pip` install. Reverted in 12c3c79e3b4e4ab88571794e3eab3c937ff9fe9d. If you wish to extend `pyproject.toml`, please create a PR with a functional version that does not break pip. See issue #566.
