### ISSUE TITLE
Suspectable lines on tests/test_tensor.cpp ?

### ISSUE THREAD

**Issue by yuki-inaho** [wjakob/nanobind#57]
Thank you for your great job. I'm enjoying your tools as combining the OpenCV framework like below repository.
It seems a very kind and sophisticated tool at least for me.
https://github.com/yuki-inaho/nanobind_opencv_exercise

## Suspectable lines (for me)
I noticed below code lines (especially the 83-th line) on the test code are a little suspectable for me.
To be exact, ``` size_t x = 0; x < tensor.shape(1); ++x ``` will be correct.
Please sorry if something is wrong, thank you.

https://github.com/wjakob/nanobind/blob/43a96c537824b4a8b5202e166c1bff239a7e547e/tests/test_tensor.cpp#L79-L87

**Comment by wjakob** [comment]
Yes, that is clearly a mistake -- thanks!
