### ISSUE TITLE
[BUG]: Get std::bad_cast when a callback return a Python complex type velue

### ISSUE THREAD

**Issue by luckymark** [wjakob/nanobind#587]
### Problem description

Get std::bad_cast when a callback return a Python complex type velue

### Reproducible example code

```text
test.py:
def callback():
    return complex(1.0,2.0)

def test_foo():
    foo(callback)

bind.cpp:
#include <nanobind/nanobind.h>
#include  <nanobind/stl/complex.h>
#include <nanobind/stl/function.h>

void foo(std::function<std::complex<double>()> func) {
    auto result = func();
}

NB_MODULE(lib_ext, module) {
    module.def("foo", &foo);
}
```

**Comment by luckymark** [comment]
I'am so sorry！
After checking my code, it turned out that I had an idiot mistake.
Thank you for your help

**Comment by bktycrg** [comment]
...Please share. I, too, am an idiot, but enough of one I'm stuck at a similar situation and haven't figured it out. :D

**Comment by luckymark** [comment]
> ...Please share. I, too, am an idiot, but enough of one I'm stuck at a similar situation and haven't figured it out. :D
@bktycrg Sorry，I can't find my error code few months ago wrote. you could paste your code and error messages here，someone maybe have a solution for you :)
