### ISSUE TITLE
Working with Pytorch?

### ISSUE THREAD

**Issue by justanhduc** [wjakob/nanobind#6]
Hi. Thanks for opening this wonderful binding tool. I have a question regarding binding Pytorch C++ codes to Python. As written in the README that Nanobind works with only "a subset of C++", can it be a drop-in for the current Pybind 11 that Pytorch is using? Have you had any experience before? If you had, could you please share? Thank you very much.

**Comment by wjakob** [comment]
> The author's time for processing GitHub issues is unfortunately very limited. Because of this, nanobind cannot accept feature requests. Furthermore, questions should not be submitted here, please use the separate "Discussions" tab. I will unfortunately need to close feature requests or questions maquerading as bug reports.
