### ISSUE TITLE
[QUESTION]: Nanobind Python Stubs

### ISSUE THREAD

**Issue by nyckmaia** [wjakob/nanobind#60]
### Problem description

I would like to build a `C++/nanobind` library that contains Python stubs, to be able to easy to use it, like the great native Python libraries (example: pandas, numpy, os, etc)

01 - Auto-complete drop down menu
-----------------------------------------

The main idea is to get the `auto-complete drop down` inside code editors like `VS Code`.

**Example:**
```
import myLib

obj  = myLib.MyClass()
obj. # here will show the drop down menu showing the MyClass public methods
```

02 - C++ Function Signatures in Python environment
-----------------------------------------------------------

Another thing is to have the functions signatures to be able to see in `VS Code` how many input arguments each `C++` function expect.

**Example:**
```
import myLib

obj = myLib.myClass()
obj.foo(    # here the editor shows the function signature
```
Question
----------

**Is there a way to get these 2 features above using `nanobind`?**

Thank you,

**Comment by nyckmaia** [comment]
Can I use `pybind11-stubgen` ([link here](https://github.com/sizmailov/pybind11-stubgen)) to generate Python stubs in a C++ project that uses `nanobind`?

**Comment by wjakob** [comment]
Stub generation is not a core feature of nanobind. If there is such an external tool for pybind11, it would likely also work for nanobind (or at least, with only small modifications). I am closing this ticket since it is not an issue, but you could feel free to open a discussion.
