### ISSUE TITLE
[BUG]: common.cpp does not compile in VS 2022 / 170

### ISSUE THREAD

**Issue by dtromb** [wjakob/nanobind#606]
### Problem description

Compilation of common.cpp fails with error 

`Lib\site-packages\nanobind\src\common.cpp(827,37):  error C2039: 'ob_digit': is not a member of '_longobject' `

### Reproducible example code

```text
#include <cstdint>
#include <nanobind/nanobind.h>
namespace nb = nanobind;
using namespace nb::literals;

NB_MODULE(MODULE_NAME, m) {
    m.doc()               = "empty test";
    m.attr("__version__") = VERSION_INFO;
}
```

**Comment by dtromb** [comment]
Python is 3.12, VS buildchain is MSBuild version 17.10.4+10fbfbf2e for .NET Framework, nanobind is 2.0.0

**Comment by wjakob** [comment]
Is it possible that you are not using CMake to build your project?

**Comment by dtromb** [comment]
I'm absolutely using CMake.

**Comment by wjakob** [comment]
The way to compile nanobind modules via CMake is through the `nanobind_add_module` function. Unfortunately, you are on your own if you deviate from this path.

For what it's worth, the part of `common.cpp` that accesses `ob_digit` is guarded by a preprocessor check for `PY_VERSION_HEX < 0x030c0000`. So only Python 11 or lower even compile this part, so that something about the explanation does not seem right to me.

**Comment by dtromb** [comment]
I am in fact using nanobind_add_module.   Look at the example source on your website - it consists of a single function, `_add_module`, which adds two numbers together and gets mapped through nanobind.  That's what I'm referring to, not `nanobind_add_module`, when I say "just the example project on the site, with the _add_module functions removed".

Just close away the ticket if you like, but your project certainly does not compile under Python 12, for even simpler use cases - /which you could have easily verified/.

You might have also looked at the place in the code in my report, and notice it is not in fact protected by an `#if`.   You might also have done a search for this error and found https://github.com/python/steering-council/issues/79  (and 3.12 sequelae) and read it.

Meanwhile I'll switch back over to pybind11 and recommend others fo the same until if/when stuf this is sorted.

**Comment by dtourolle** [comment]
So @dtromb  you are using an out of date version of nanobind.
Line 827 of common in master does not have the code in your compiler error. The version 0.3.0 on the other hand has the line:
https://github.com/wjakob/nanobind/blob/2bd6e48836a4bd1c9407cdb7277e80d327e1d736/src/common.cpp#L827
vs
https://github.com/wjakob/nanobind/blob/master/src/common.cpp#L827

Try pulling a later version of nanobind or downgrading your python to <=3.11.

**Comment by dtourolle** [comment]
> You might have also looked at the code citation in my report, and notice it is not in fact protected by an `#if`. You might also have done a search for this error and found [python/steering-council#79](https://github.com/python/steering-council/issues/79) (and 3.12 sequelae) and read it.

I am in no way involved in nanobind, but before I write anything suggesting more work for an unpaid maintainer I think of this [image](https://xkcd.com/2347/). This kind of meditation can also clear my mind to help do things like check the git version of my code ;)
