### ISSUE TITLE
[BUG]:  ob_digit

### ISSUE THREAD

**Issue by edselmalasig** [wjakob/nanobind#610]
### Problem description

nanobind/src/common.cpp:827:37: error: no member named 'ob_digit' in '_longobject'
                digit value_d = lo->ob_digit[0];

**Comment by dtourolle** [comment]
I'd recommend checkingout/pulling the latest master branch.  the ob_digit issue is related to a change between python 3.11 and python 3.12 and the latest version of nanobind solves this. I ran into the same issue with an older version of nanobind (used by nanogui) and python3.12.

> https://github.com/wjakob/nanobind/blob/master/src/common.cpp#L827

is this in the master which is completely different: https://github.com/wjakob/nanobind/blob/master/src/common.cpp#L827

**Comment by wjakob** [comment]
Thanks @dtourolle!
