### ISSUE TITLE
[BUG]: None argument not handled for built-in types

### ISSUE THREAD

**Issue by wojdyr** [wjakob/nanobind#655]
### Problem description

A function that takes argument `int*`, `const char*` or `std::string*` doesn't accept None even if `.none()` is specified.

Passing None works for `struct Foo*`. In pybind11, it works ~~for all types~~ additionally for `char*`.

### Reproducible example code

```cpp
m.def("string_none", [](std::string *p) { return !p; }, "p"_a.none());
m.def("int_none", [](int *p) { return !p; }, "p"_a.none());
m.def("cstring_none", [](const char *p) { return !p; }, "p"_a.none());
```
```python
t.string_none(None)
t.int_none(None)
t.cstring_none(None)
```
Each of the functions above ends with an error message like this:
```
>       t.int_none(None)
E       TypeError: int_none(): incompatible function arguments. The following argument types are supported:
E           1. int_none(p: typing.Optional[int]) -> bool
E       
E       Invoked with types: NoneType
```

**Comment by wjakob** [comment]
his change is intentional in nanobind, where it simplified the type casters and function dispatch loop. To accomplish your goal, you would have to wrap the pointers in `std::optional` or similar types in other frameworks. If you absolutely need this functionality, then I suggest to use the more general pybind11 framework. (nanobind is designed to be tiny+fast, and that entails dropping features sometimes)

**Comment by wojdyr** [comment]
I appreciate it's tiny and fast – that's why I migrating to nanobind.
The current behavior is actually documented, I just missed it before opening this issue.

That said, I tested it quickly and I believe that all that's needed to convert None->nullptr for `char*` (pybind11 also doesn't handle None for built-in types, but makes exception for `char*`) would be one line change in this error-handling branch:

```diff
--- a/include/nanobind/nb_cast.h
+++ b/include/nanobind/nb_cast.h
@@ -284,7 +284,7 @@ template <> struct type_caster<char> {
         value = PyUnicode_AsUTF8AndSize(src.ptr(), &size);
         if (!value) {
             PyErr_Clear();
-            return false;
+            return src.is_none();
         }
         return true;
     }
```
No problem if you prefer to not handle None here, though. The workaround with std::optional is also good.
