### ISSUE TITLE
[BUG]: nb::enum_ does not have def_prop_ro_static in 2.0.0

### ISSUE THREAD

**Issue by cheng-openai** [wjakob/nanobind#660]
### Problem description

def_static is also missing, but it's already fixed in https://github.com/wjakob/nanobind/issues/597.

**Comment by wjakob** [comment]
Dear Cheng,

this issue is likely not fixable because the redesigned enum bindings in nanobind v2 are based on the Python native enum classes. These don’t use the nanobind metaclass, which is a prerequisite for bindings of static attributes.

**Comment by wjakob** [comment]
Maybe something could be done by inheriting from enum.EnumMeta and patching in some kind of support for static properties. However, I am not inclined to add such a change to nanobind. Indeed, the main point of the refactor was to make enum bindings behave just like standard Python enums.

**Comment by cheng-openai** [comment]
Thank you Wenzel, I'll look for a workaround on my use case.
