### ISSUE TITLE
[BUG]: Assertion information not shown in stack trace

### ISSUE THREAD

**Issue by schnellerhase** [wjakob/nanobind#666]
### Problem description

Compiling a python module in `Debug` mode and triggering an assertion from a python script results in an inexpressive error output. Especially not hinting it's the result of an assertion, nor which one. (The windows case seems to be even worse, since it doesn't even crash - see CI of PR below)

Encountered during debugging such a case in dolfinx https://github.com/FEniCS/dolfinx/pull/3331

### Reproducible example code

Behavior is reproduced in https://github.com/schnellerhase/nanobind_example/pull/1.

This PR alters the nanobind example by an always triggered assertion and compiles (in the pip CI run) the python module in Debug mode, yielding the observed behavior.

**Comment by wjakob** [comment]
This issue is not at all related to nanobind. The C `assert()` macro prints an error to `stderr` and then calls `abort()`. Given how `pytest` actively tries to captures text from extensions to group it with testcase output, this means that such messages are completely lost from platforms. You'll likely want to create your own assertion framework that is better-behaved.

**Comment by schnellerhase** [comment]
Thanks for the clarification, indeed passing `--capture=sys` to `pytest` shows the captured output from `stderr`. (The windows run still gets stuck though)

Is it not desirable to have the assertion mapped from the c style assertion back to a python `AssertionError` which then also `pytest` would capture (or any other python assertion handling)?

**Comment by wjakob** [comment]
When somebody calls `abort()`, it's over. You just cannot use C-style assertions if you want them to play well with Python. Let's reserve this issue tracker for things that are actual nanobind issues.
