### ISSUE TITLE
[BUG]: The "Creating your first extension" section in the documentation doesn't explain how to create CMakeLists.txt

### ISSUE THREAD

**Issue by yurivict** [wjakob/nanobind#679]
### Problem description

Instructions [here](https://nanobind.readthedocs.io/en/latest/basics.html) ask to create the file my_ext.cpp and then to run "cmake -S . -B build".

The cmake command fails:
```
$ cmake -S . -B build
CMake Error: The source directory "/usr/ports/devel/py-nanobind" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
because cmake (of course) expects CMakeLists.txt which the section "Creating your first extension" doesn't explain how to create.

-------------

Should cmake even be required?
Shouldn't nanobind work as a headers-only C++ library?
pybind11 works as a headers-only C++ library which is very simple, convenient and easy to understand. Why doesn't nanobind work the same way?

**Comment by wjakob** [comment]
These things are explained in the documentation, in the section "Why another binding library"
