### ISSUE TITLE
[OTHER]: support `__members__` in `nb::enum_`

### ISSUE THREAD

**Issue by cheng-openai** [wjakob/nanobind#689]
can `nb::enum_` support `__members__` by default? we currently work around this by `def_prop_ro_static` on our own, but 2.1.0's `nb::enum_` does not support `def_prop_ro_static`.

**Comment by wjakob** [comment]
It seems to work fine to me. The new enum implementation is just a thin wrapper around the built-in Python `enum` module.

```
>>> test_enum_ext.Enum.__members__
mappingproxy({'A': Enum.A, 'B': Enum.B, 'C': Enum.C})
```

Please don't create issues unless you are certain to have found a problem with nanobind. Use the discussion tab for questions.
