### ISSUE TITLE
[BUG]: Incorrect file extension generated for .pyd file when specifying Python version

### ISSUE THREAD

**Issue by MrDengDengDeng** [wjakob/nanobind#773]
### Problem description

When specifying a specific Python version, the generated .pyd file has an incorrect suffix. The extension does not match the expected format for the targeted Python version, which leads to compatibility issues during module loading.
The .pyd file suffix issue was resolved by adjusting the regular expression in the if statement. I changed ".+-.+-.+" to ".+-.+_.+", and with this modification, the generated file name now has the correct suffix. Here’s the updated code:
`if(DEFINED NB_SOABI AND "${NB_SOABI}" MATCHES ".+-.+_.+")`
 `  set(NB_SUFFIX ".${NB_SOABI}${NB_SUFFIX_EXT}")`
`endif()`

### Reproducible example code

```text
cmake_minimum_required(VERSION 3.21)

project(Test VERSION 0.1.0 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)

set(Python_ROOT_DIR "${CMAKE_SOURCE_DIR}/venv312")

find_package(Python 3.12 COMPONENTS Interpreter Development REQUIRED)

find_package(Nanobind REQUIRED PATHS "${CMAKE_SOURCE_DIR}/venv312/Lib/site-packages/nanobind/cmake" NO_DEFAULT_PATH)

# if(DEFINED NB_SOABI AND "${NB_SOABI}" MATCHES ".+-.+_.+")
#   set(NB_SUFFIX ".${NB_SOABI}${NB_SUFFIX_EXT}")
# endif()

Message(STATUS "NB_SOABI: ${NB_SOABI}") # prints: cp312-win_amd64
Message(STATUS "NB_SUFFIX: ${NB_SUFFIX}") # prints:.cp311-win_amd64.pyd
```

**Comment by wjakob** [comment]
Could I ask you to make a PR with this change to `cmake/nanobind-config.cmake`? Then we can see if this impacts all the various targets.

**Comment by wjakob** [comment]
I don't know how to solve this issue on my own, and things seem stuck. It does not seem to affect many people (first time this came up). Will close for now, please reopen if you have additional information or a proposed fix.

**Comment by mtsokol** [comment]
I also experienced this. In `cibuildwheel` that build LLVM for python 3.10 and 3.11, in 3.11 build the Python version was incorrect `cp310-win_amd64.pyd` instead of `cp311-win_amd64.pyd`.

I managed to solve it by calling `cmake` with addtional `-UNB_SUFFIX` and `-UNB_SUFFIX_S`.
