### ISSUE TITLE
[BUG]: Custom __new__ with no arguments

### ISSUE THREAD

**Issue by WKarel** [wjakob/nanobind#786]
### Problem description

The docs provide an [example](https://nanobind.readthedocs.io/en/latest/classes.html#customizing-python-object-creation) on how to customize object creation, including an overload with no arguments. But without arguments, instantiation fails - see code below.

There seems to be some code and/or comments out of sync:
- if new_ is called on a function without arguments, then wrap_base_new creates a wrapper with 1 argument, while
- nb_type_vectorcall seems to assume that this wrapper has none.
- test46_custom_new even tests that this wrapper can be called with the class as argument.

Given the above, I do not see how using new_ on a function without arguments is meant to work.

### Reproducible example code

```cpp
class Pet
{
    Pet(){}
public:
    static std::unique_ptr<Pet> make(std::string name, int age) {
        return std::unique_ptr<Pet>{ new Pet() };
    };
};

nb::class_<Pet>(test, "Pet")
    .def(nb::new_([]() { return Pet::make("charly", 0); }))
    .def(nb::new_(&Pet::make), "name"_a, "age"_a);
```

```py
>>> from mod import Pet
>>> p = Pet("charly", 0)
>>> p = Pet()
TypeError: __new__(): incompatible function arguments. The following argument types are supported:
    1. __new__(cls: object, name: str, age: int) -> mod.Pet

Invoked with types:

```
```

**Comment by oremanj** [comment]
This looks like a bug in the recently(ish) added support for type vectorcall; it’s not properly identifying whether a user-defined new can accept zero arguments. I’m working on a fix.

**Comment by agarny** [comment]
This does indeed correspond to what I have just mentioned in a [discussion](https://github.com/wjakob/nanobind/discussions/787) a few hours ago.

FWIW, it's all fine using nanobind 2.1.0.
