### ISSUE TITLE
clarify nanobind_add_module?

### ISSUE THREAD

**Issue by truher** [wjakob/nanobind#797]
https://github.com/wjakob/nanobind/blob/c2e394eee5d19816871151de43c29b4051fbf9ff/docs/building.rst?plain=1#L92

Hi, I'm just starting to use nanobind (and pybind), and I appreciate everything you've done.

I have one tiny suggestion, which is that the doc linked above might make it more clear that you have to specify *all* the source files in the nanobind_add_module() directive.

I had a C++ implementation, and a separate "stand off" cpp file full of NB_MODULEs, and i thought it would  be sufficient to just include the latter in nanobind_add_module(), and rely on cmake and the linker to wire it all up.  This is apparently not the way it works.  :-)

So, like, the current text says "Any number of source code and header files can be declared " and you could instead say something stronger like "All implemenation files *must* be declared," and maybe show an example with more than one?

Thanks again!

**Comment by wjakob** [comment]
Can you open a PR with your proposed documentation change? This isn't really an issue of the library, so I will close this ticket.
