### ISSUE TITLE
Data is getting corrupted randomly by the time it reaches to python

### ISSUE THREAD

**Issue by prashant-saxena** [wjakob/nanobind#801]
### Problem description

Data is getting corrupted randomly by the time it reaches to python.

### Reproducible example code

I am providing a snippet of the code. I cannot provide the full working code right now but if it would be needed then I would make it. 

```cpp
nb::ndarray<nb::numpy, int32_t> decompress(nb::bytes bytes) {
...
std::unique_ptr<int32_t> dest(new int32_t[num_elem]);
...
for (size_t i = 0; i < num_elem; i++) {
    std::cout << dest.get()[i] << ", ";
}
return nb::ndarray<nb::numpy, int32_t>(dest.get(), {num_elem});
}
```
On python side when you print the returned array
```text
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 

[-24027360       452 -69347088       452         5         6         7
         8         9        10        11        12        13        14
        15        16        17        18        19        20        21
        22        23        24        25        26        27        28
        29        30]
```
The first 1-30 values are printed from c++ for loop and second one is returned array. This behavior is random. You run code around 10 times and it would produce the correct result but suddenly you see corruption. Secondly, only first four values are getting corrupted all the times.

**Comment by wjakob** [comment]
Please review the ndarray documentation on ownership carefully, it explains exactly this issue and how to solve it.
