### ISSUE TITLE
[OTHER]: Changelog for v2.4.0

### ISSUE THREAD

**Issue by marbre** [wjakob/nanobind#811]
### Please don't use.

The recent changelog refers to version 2.3.0, https://nanobind.readthedocs.io/en/latest/changelog.html#version-2-3-0-dec-6-2024, which was added as part of https://github.com/wjakob/nanobind/commit/86128b9cc7408a9a05ef082045a280c2ee6c3209#diff-b7f8a8784d5eff6e6b1b2c2529b831cd86132c49699fe48e0d23c17ad4e2d7deR18, but the latest release was 2.4.0. I assume it should be version 2.4.0 in the changelog.

**Comment by wjakob** [comment]
Oops, that's annoying. I accidentally skipped over version 2.3.0. This is now documented in the changelog.
