### ISSUE TITLE
[BUG]: ND array casting behavior change from 2.2 to 2.4

### ISSUE THREAD

**Issue by awni** [wjakob/nanobind#818]
### Problem description

The casting to contiguous array behavior changed from Nanobind 2.2 to Nanobind 2.4 and it breaks code in MLX when we try to update. I'm not sure if this is a bug.. but the change is unexpected and seems somewhat counter to the descriptino in the Nanobind [documentation](https://nanobind.readthedocs.io/en/latest/ndarray.html#overload-resolution):

> When no perfect match can be found, nanobind will try each overload once more while performing basic implicit conversions: it will convert strided arrays into C- or F-contiguous arrays (if requested) and perform type conversion. T

Specifically if you have a variant with a contiguous nd array and an `nb::object` in 2.2 it would cast and copy to the array and in 2.4 it does not.

### Reproducible example code

The C++ code:

```c++
#include <iostream>
#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/stl/variant.h>

namespace nb = nanobind;

using InitType = std::variant<
    nb::ndarray<nb::ro, nb::c_contig, nb::device::cpu>,
    nb::object>;

NB_MODULE(my_ext, m) {
    m.def(
        "convert",
        [](InitType v) {
          if (auto pv = std::get_if<
                         nb::ndarray<nb::ro, nb::c_contig, nb::device::cpu>>(&v);
                     pv) {
            std::cout << "Worked! " << std::endl;
          } else {
            std::cout << "Failed! " << std::endl;
          }
        },
        nb::arg()
    );
}
```

The Python code:
```python
import numpy as np
import sys
sys.path.append("build/")
import my_ext

np_arr = np.random.uniform(size=(10, 10)).astype(np.complex64)
np_arr = np_arr.T
my_ext.convert(np_arr) # <-- Used to work now prints "Failed"
```

**Comment by wjakob** [comment]
I am a bit swamped with other work at the moment. Could I ask you to bisect this to a specific commit?

**Comment by wjakob** [comment]
Could this be due to PR #769?

**Comment by awni** [comment]
Yes indeed, it works before that PR and breaks after it (building on 3528abf664e4385b083843729b79d351118f11e9).

**Comment by wjakob** [comment]
Adding @tjstum

**Comment by wjakob** [comment]
Looking at this more carefully, I think that this behavior is actually correct. Your array requires an implicit conversion from f-style to c-style ordering, and in that case the `nb::object` from the variant binds more strongly (in the first overload resolution phase).

To get the behavior you want, you will need to implement some kind of "last-resort" caster to nb::object.

You can do this by implementing a custom Python object (e.g. ``nb::fallback_object`) with a type caster (similar to the one from `nb::object`) that only performs a successful cast if an implicit conversion is requested.

**Comment by tjstum** [comment]
Thanks @wjakob!

@awni: another approach is to write a lambda that accepts `nb::object` and do the casting in there (with `nb::try_cast` or `nb::cast`), which will permit the implicit conversion you're after.

**Comment by awni** [comment]
Thanks for the comments! Yes the new behavior makes sense, we'll aim to work around it. 

@tjstum I'm not following your suggestion. Do you mind elaborating?

**Comment by wjakob** [comment]
If there is a lot of code, going via the route of a custom caster is probably easier since you just need to write it once. `try_cast` would just work if the codebase is rewritten to take `nb::object` everywhere, with casting being done on the user's side. In this case, the type information and extracted stubs would be quite rudimentary (only referencing `object`).

I will close this issue since there doesn't seem to be a problem with nanobind.

**Comment by awni** [comment]
Yes, I understand now. Thanks! I ended up going with @wjakob suggestion which was not too involved.
